---
# Add this snippet to the top of your playbook.
# It will install python2 if missing (but checks first so no expensive repeated apt updates)
# gwillem@gmail.com
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: webservers
  vars:
    site: paperquik

  tasks:
    # Update repositories cache and install several packages I need or like to
    # have (for example, I use emacs rather than vi).
    - apt: pkg={{item}} state=installed update_cache=yes
      with_items:
        - apache2
        - emacs24
        - git
        - unzip

    # Enable Apache modules we'll be using.
    - apache2_module: name={{item}} state=present
      with_items:
        - expires
        - headers
        - rewrite
        - proxy_http
      notify:
        - restart apache2

    # Copy the virtual host file needed for Apache.
    - copy: src={{site}}.conf dest=/etc/apache2/sites-available/

    # Disable the default Apache site.
    - command: a2dissite 000-default
      args:
        removes: /etc/apache2/sites-enabled/000-default.conf
      notify:
        - restart apache2

    # Enable the site on Apache so it starts serving it up.
    - command: a2ensite {{ site }}
      args:
        creates: /etc/apache2/sites-enabled/{{ site }}.conf
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
