---
- hosts: webservers
  vars:
    site: paperquik
  sudo: no
  tasks:
    # Copy everything inside the dist directory to the directory Apache is
    # serving up.
    # - copy: src=dist/ dest=/var/www/{{ site }}
    - synchronize: src=dist/ dest=/var/www/{{ site }}/
                   recursive=yes
